name: "Docs"

on:
  push:
    paths:
      - docs/**
      - mkdocs.yaml
      - .github/workflows/docs.yaml
  workflow_dispatch:

jobs:
  deploy_docs:
    name: "Deploy Docs"
    runs-on: ubuntu-latest
    concurrency: deploy-docs-${{ github.ref }}
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Install poetry"
        run: pipx install poetry

      - name: "Get python version"
        id: python
        run: echo "version=$(yq .tool.poetry.dependencies.python pyproject.toml)" >> "$GITHUB_OUTPUT"

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python.outputs.version }}
          cache: "poetry"

      - name: "Install dependencies"
        run: poetry install --only docs

      - name: "Build & Deploy 🚀"
        run: poetry run mkdocs gh-deploy --force
        env:
          SITE_DESCRIPTION: ${{ github.event.repository.description }}
